"""empty message

Revision ID: 3bb225521949
Revises: 70858431de6e
Create Date: 2024-04-17 18:48:23.905123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bb225521949'
down_revision: Union[str, None] = '70858431de6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('room_id', sa.Integer(), nullable=False))
    op.drop_constraint('images_room_fkey', 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'rooms', ['room_id'], ['id'])
    op.drop_column('images', 'room')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('room', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key('images_room_fkey', 'images', 'rooms', ['room'], ['id'])
    op.drop_column('images', 'room_id')
    # ### end Alembic commands ###
