"""create relatioship for hotel and ro

Revision ID: cf0344c440f7
Revises: 0d5f0cab7c3e
Create Date: 2024-03-05 19:40:54.040317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf0344c440f7'
down_revision: Union[str, None] = '0d5f0cab7c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
